### ISSUE TITLE
"Something went wrong" error

### ISSUE THREAD

**Issue by acereser** [mckaywrigley/ai-code-translator#24]
Hello, when I try running the web app I get the error "Something went wrong". This happens both with https://ai-code-translator.vercel.app/ and if I use the app locally (tested: Windows 10). Is there anything I should do to fix the issue? Thanks
<img width="1328" alt="Web_UI" src="https://user-images.githubusercontent.com/129725202/230275017-9737834a-56c5-4685-b431-8f3ecfc9c899.PNG">

**Comment by OrcVole** [comment]
Same problem here

**Comment by ubestbsteppin** [comment]
You need a payed Open AI API account

**Comment by acereser** [comment]
@ubestbsteppin Thank you for the hint! I confused the ChatGPT key with the OpenAI API key ;-)
