### ISSUE TITLE
Pascal language?

### ISSUE THREAD

**Issue by fredvs** [mckaywrigley/ai-code-translator#4]
Hello.

Nice project!
Do you have plan for conversion from/to Pascal language?
Pascal is still highly used ( Delphi, Free Pascal, Turbo Pascal, ...)
( And ChatGPT can deal with it. )
Fre;D

**Comment by mckaywrigley** [comment]
If you make a PR to add it in the list I'll merge. It's in the CodeBlock component.

**Comment by LZL0** [comment]
The project is such a cool idea!

**Comment by fredvs** [comment]
Huh, sorry, what is a PR ?

**Comment by fredvs** [comment]
I dont see what to add in CodeBlock component.tsx.
But I see  something in LanguageSelect.tsx.

Do you want to add this ?:

```
const languages = [
  { value: 'Pascal', label: 'Pascal' },

```

**Comment by mckaywrigley** [comment]
Ah yes sorry - forgot i moved it!
